#Name: Maansinh Jadeja
#Student Number: 101157121

import sys

'''
Q.1
I do not believe it, as chatgpt has probably searched the internet for similar pieces of code in order to generate the solution,
so the fact that it tells us the code is offered without specific licensing terms or usage restrictions. The code was most likely
made by another person that published their work on the net, and they hold the rights to the piece of code. 

The consequences of code generated by chatGPT is that the code may not be completely accurate, as I had to ask multiple times for
chatGPT to give me an accurate working function. Another consequence is that, as mentioned before, this code may look rather similar
to another person's code published on the net, so it may be more likely for you to get flagged with copying someone else's 
implementation.

Q.2
I do not think there is a bias towards a particular ethinicity as the list generated had names from different ethnicities such as
english, portuguese, indian.

List of surnames for chatGPT program: 
Adams
Anderson
Baker
Brown
Carter
Cooper
Davis
Edwards
Franklin
Garcia
Gonzalez
Hall
Harris
Ingram
Jackson
Johnson
Kennedy
Kim
Lee
Lopez
Martinez
Mitchell
Nelson
Nguyen
O'Connor
Olson
Parker
Patel
Quinones
Quinn
Ramirez
Reyes
Rodriguez
Singh
Smith
Taylor
Turner
Upton
Vasquez
Vega
Walker
Williams
Xu
Yang
Young
Zhang
Zimmerman

List of 51 surnames from Russia: 
Ivanov
Petrov
Smirnov
Sidorov
Popov
Kuznetsov
Sokolov
Lebedev
Kozlov
Novikov
Morozov
Volkov
Alekseev
Fedorov
Nikolaev
Orlov
Volkov
Semyonov
Frolov
Andreev
Kiselev
Spiridonov
Markov
Gusev
Titov
Tikhonov
Bondarev
Ponomarev
Grigoriev
Suvorov
Vasiliev
Zaytsev
Volkov
Korolev
Yudin
Belyakov
Denisov
Gavrilov
Shirokov
Efimov
Maksimov
Demidov
Dementiev
Nikitin
Mironov
Lykov
Smirnov
Kulikov
Polakov
Pavlov
Grachev

'''
#ChatGPT generated program
def determine_position_in_percentiles(name: str) -> str:
    """
    Determine the position of a given name relative to the 25%, 50%, and 75% names.

    Parameters:
        name (str): The name to check.

    Returns:
        str: A message indicating the sorting position of the given name.
    """
    # Percentiles
    name_25_percentile = "Hall"
    name_50_percentile = "O'Connor"
    name_75_percentile = "Upton"

    # Determine the position of the name
    if name < name_25_percentile:
        return f"{name} should be sorted before the 25% name."
    elif name_25_percentile <= name < name_50_percentile:
        return f"{name} should be sorted between the 25% and 50% names."
    elif name_50_percentile <= name < name_75_percentile:
        return f"{name} should be sorted between the 50% and 75% names."
    else:
        return f"{name} should be sorted after the 75% name."

    '''
    Licensing terms or usage restrictions associated with the above generated code:

    The code provided is offered without specific licensing terms or usage restrictions. 
    You are free to use, modify, and distribute the code for personal, educational, or commercial purposes. 
    There are no restrictions on the use of the code.

    It's important to note that while the code is provided without restrictions, you should use it responsibly and ethically. 
    Additionally, consider best practices and adhere to applicable laws and regulations when incorporating code into your projects. 
    If you have specific legal or licensing requirements, it's advisable to consult with legal professionals for guidance.
    '''


def main():

    # Example usage:
    name_to_check = "Garcia"
    result = determine_position_in_percentiles(name_to_check)
    print(result)


    userSurname="" 

    while(True): #Post-condition loop
     
        print()
        userSurname=input("Please input a name to check for the position (-1 to quit): ") #Prompt user to input surname repeatedly till they input -1 to quit
        if(userSurname=="-1"):
            break
        else:
            #call function here
            result2 = determine_position_in_percentiles(userSurname)
            # print(f"Position of the given name {userSurname} is {result}")
            print(result2) 


main()


